name: Codesniffer
on: [pull_request]
env:
    PHP_VERSION: "8.5"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.PHP_VERSION }}
                tools: cs2pr
            - uses: ramsey/composer-install@v3
            - name: run phpcs
              run: vendor/bin/phpcs -q --report=checkstyle src | cs2pr
