name: static analysis
on: [pull_request]
env:
    PHP_VERSION: "8.5"

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.PHP_VERSION }}
            - uses: ramsey/composer-install@v3
            - run: composer phpstan
